polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path('', views.index, name='index'),
    path('redSoon/', views.redSoon, name='redSoon'),
    path('yellowSoon/', views.yellowSoon, name='yellowSoon'),
    path('time/', views.time, name='time'),
    path('time/<str:time>', views.time, name='time'),
]

story1/urls.py
from django.urls import path
from . import views

app_name = "story1"

urlpatterns = [
    path('', views.home, name='home'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('story1/', include('story1.urls')),
    path('course/', include('testform1.urls')),
    path('event/', include('story6.urls')),
    path('admin/', admin.site.urls),
]

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.indexEvent, name='indexEvent'),
    path('addEvent/', views.addEvent, name='addEvent'),
    path('addMember/<str:id>', views.addMember, name='addMember'),
    path('deleteMember/<str:id>', views.deleteMember, name='deleteMember')

]

testform1/urls.py
from django.urls import path
from . import views

app_name = "matakuliah"


urlpatterns = [
    path('', views.index, name='index'),
    path('show/<str:order>/', views.show, name='show'),
    path('showAdmin/<str:order>/', views.showAdmin, name='showAdmin'),
    path('create', views.create, name='create'),
    path('indexAdmin', views.indexAdmin, name='indexAdmin'),
    path('indexAdmin/<str:order>/', views.indexAdmin, name='indexAdmin'),
]

polls/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Member(models.Model):
    name = models.CharField(max_length=50)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

testform1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MataKuliah(models.Model):
    order = models.AutoField(primary_key=True)
    namaMatkul = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    jumlahSKS = models.IntegerField()
    deskripsiMatkul = models.TextField()
    waktu = models.CharField(max_length=50)
    semester = models.CharField(max_length=100)

    def __str__(self):
        return self.namaMatkul
    
    def snippet(self):
        return self.deskripsiMatkul[0:150] + "..."

class Tugas(models.Model):
    namaTugas = models.CharField(max_length=100)
    tanggal = models.DateTimeField(auto_now=False, auto_now_add=False)
    deskripsiTugas = models.TextField()
    matakuliah = models.ForeignKey(MataKuliah, on_delete=models.CASCADE)

    def __str__(self):
        return self.namaTugas

story6/forms.py
from django import forms
from .models import Event, Member

class CreateEvent(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name']

class CreateMember(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name', 'event']

testform1/forms.py
from django import forms
from . import models

class CreateMatkul(forms.ModelForm):
    class Meta:
        model = models.MataKuliah
        fields = ['namaMatkul', 'dosen', 'jumlahSKS', 'deskripsiMatkul', 'waktu', 'semester']

polls/views.py
import datetime
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, "index.html", {'static' : 'true', 'color' : 'none'})
def redSoon(request):
    color = 'red'
    return render(request, "redSoon.html", {'color' : color})
def yellowSoon(request):
    color = 'yellow'
    return render(request, "yellowSoon.html", {'color' : color})
def time(request, time = '0'):
    time = int(time)
    time = time + 7
    TIME_ZONE = datetime.datetime.now() + datetime.timedelta(hours = time)
    return render(request, "time.html", {'time' : TIME_ZONE})

story1/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

story6/views.py
from django.shortcuts import render, redirect
from .forms import CreateEvent, CreateMember
from .models import Event, Member

# Create your views here.
def indexEvent(request):
    event = Event.objects.all()
    member = Member.objects.all()
    return render(request, 'eventList.html', {'event' : event, "member" : member})

def addEvent(request):
    if request.method == 'POST':
        form = CreateEvent(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story6:indexEvent')
    return render(request, 'addEvent.html')

def addMember(request, id = 0):
    id = int(id)
    event = Event.objects.get(id=id)
    if request.method == 'POST':
        id = request.POST['eventId']
        name = request.POST['name']
        event = Event.objects.get(id=id)
        data = {'name' : name, 'event' : event}
        form = CreateMember(data=data)
        if form.is_valid():
            form.save()
            return redirect('story6:indexEvent')
    return render(request, 'addMember.html', {'event' : event})

def deleteMember(request, id):
    id = int(id)
    member = Member.objects.get(id=id)
    member.delete()
    return redirect('story6:indexEvent')

testform1/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah, Tugas
from . import forms
import datetime

# Create your views here.
def index(request):
    matakuliah = MataKuliah.objects.all()
    return render(request, 'matkul.html', {'matakuliah' : matakuliah})

def show(request, order):
    order = int(order)
    matakuliah = MataKuliah.objects.get(order=order)
    tugas = Tugas.objects.filter(matakuliah=matakuliah)
    today = datetime.datetime.now().timestamp()
    masihLama = []
    besok = []
    udahLewat = []
    for item in tugas:
        if item.tanggal.timestamp() < today:
            udahLewat.append(item)
        elif item.tanggal.timestamp() < today + 86400:
            besok.append(item)
        else:
            masihLama.append(item)

    return render(request, "show.html", {"matakuliah" : matakuliah, "besok" : besok, "udahLewat" : udahLewat, "masihLama" : masihLama})

def showAdmin(request, order):
    order = int(order)
    matakuliah = MataKuliah.objects.get(order=order)
    return render(request, "showAdmin.html", {"matakuliah" : matakuliah})

def create(request):
    if (request.method == 'GET'):
        form = forms.CreateMatkul()
        return render(request, "create.html", {'form' : form})
    elif (request.method == 'POST'):
        form = forms.CreateMatkul(request.POST)
        if form.is_valid():
            form.save()
            return redirect('matakuliah:index')

def indexAdmin(request):
    if request.method == "POST":
        order = request.POST["order"]
        matakuliah = MataKuliah.objects.get(order=order)
        matakuliah.delete()
        return redirect('matakuliah:indexAdmin')
    else:
        matakuliah = MataKuliah.objects.all()
        return render(request, 'indexAdmin.html', {'matakuliah' : matakuliah})

polls/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block tittle %} Home Page {% endblock tittle %}

{% block content %}
    <!-- background 1 -->
    <section class="background1">
        <span>MUHAMMADHAFIZMAULANA</span>
        <span>MUHAMMADHAFIZMAULANA</span>
        <span>MUHAMMADHAFIZMAULANA</span>
        <span>MUHAMMADHAFIZMAULANA</span>
        <span>MUHAMMADHAFIZMAULANA</span>
        <span>MUHAMMADHAFIZMAULANA</span>
        <span>MUHAMMADHAFIZMAULANA</span>
    </section>
    <!-- endsection -->
    <!-- section home -->
    <section class="home-greeting">
        <h1>MUHAMMAD HAFIZ MAULANA.</h1>
    </section>
    <!-- endsection -->
    <!-- section about-->
    <section class="about" id="about">
        <div class="gambar">
            <span>ABOUT.</span>
        </div>
        <div class="paragraph">
            <div class="background2">
                <span>HELLO.</span>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat sequi perspiciatis officia adipisci debitis dolores nisi, non itaque voluptatum minus distinctio tempora. Sed dicta assumenda dolorum at corrupti quae. Dolore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi vitae doloribus, voluptatem voluptate tempore, cum necessitatibus inventore minima molestiae at itaque beatae cumque eius similique quaerat nesciunt dolorem praesentium quod.
            </p>
            <div class="background2">
                <span>HELLO.</span>
            </div>
        </div>
        <div class="link" onclick="location.href='{% url 'polls:redSoon' %}'">
            <span>MORE</span>
            <div class="arrow">
                <span></span>
                <span></span>
            </div>
        </div>
    </section>
    <!-- endsection -->
    <!-- section project -->
    <section class="project" id="project">
        <div class="header">PROJECT.</div>
        <div class="gallery">
            <div class="item" data-toggle="modal" data-target="#studioink">STUDIOINK</div>
            <div class="item" data-toggle="modal" data-target="#bismit">BISMIT FASILKOM</div>
            <div class="item" data-toggle="modal" data-target="#comingsoon">COMINGSOON</div>
            <div class="item" data-toggle="modal" data-target="#comingsoon">COMINGSOON</div>
            <div class="item" data-toggle="modal" data-target="#comingsoon">COMINGSOON</div>
            <div class="item" data-toggle="modal" data-target="#comingsoon">COMINGSOON</div>
        </div>
        <div class="link" onclick="location.href='{% url 'polls:yellowSoon' %}'">
            <span>MORE</span>
            <div class="arrow">
                <span></span>
                <span></span>
            </div>
        </div>
    </section>
    <!-- endsection -->
    <!-- Carosel Section -->
    <div class="pop-up">
        <div class="modal fade" id="studioink" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Challange</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="carousel-item active">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (7).png' %}" alt="First slide">
                              </div>
                              <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (8).png' %}" alt="Second slide">
                              </div>
                              <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (9).png' %}" alt="Third slide">
                              </div>
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="sr-only">Next</span>
                            </a>
                          </div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="bismit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Challange</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <div id="bismitcarousel" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#bismitcarousel" data-slide-to="0" class="active"></li>
                              <li data-target="#bismitcarousel" data-slide-to="1"></li>
                              <li data-target="#bismitcarousel" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="carousel-item active">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (2).png' %}" alt="First slide">
                              </div>
                              <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (3).png' %}" alt="Second slide">
                              </div>
                              <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (4).png' %}" alt="Third slide">
                              </div>
                            </div>
                            <a class="carousel-control-prev" href="#bismitcarousel" role="button" data-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#bismitcarousel" role="button" data-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="sr-only">Next</span>
                            </a>
                          </div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="comingsoon" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Challange</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <div id="comingsooncarousel" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#comingsooncarousel" data-slide-to="0" class="active"></li>
                              <li data-target="#comingsooncarousel" data-slide-to="1"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="carousel-item active">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (5).png' %}" alt="First slide">
                              </div>
                              <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'main/img/Screenshots/Screenshot (6).png' %}" alt="Second slide">
                              </div>
                            </div>
                            <a class="carousel-control-prev" href="#comingsooncarousel" role="button" data-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#comingsooncarousel" role="button" data-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="sr-only">Next</span>
                            </a>
                          </div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--  -->
{% endblock content %}

story6/templates/eventList.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/styles/course.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock css %}

{% block tittle %}Event List{% endblock tittle %}

{% block content %}
<div class="courses">
    <div class="header"><h1>Event</h1></div>
    <button type="button" class="btn btn-primary btn-lg my-2" onclick="location.href='{% url 'story6:addEvent' %}'">Add Event</button>
    {% if event is not none %}
        <div class="table">
            {% for i in event %}
            <div class="card">
                <h5 class="card-header">{{ i.name }}</h5>
                <div class="card-body">
                <h5 class="card-title">Member :</h5>
                <ul class="list-group">
                {% for j in member %}
                    {% if j.event == i %}
                        <li class="list-group-item d-flex justify-content-between">
                            <span>{{j.name}}</span>
                            <a class="material-icons text-danger text-decoration-none" href="{% url 'story6:deleteMember' j.id %}">delete_outline</a>
                        </li>
                    {% endif %}
                {% endfor %}
                </ul>
                <button type="button" class="btn btn-info my-2" onclick="location.href='{% url 'story6:addMember' id=i.id %}'">Add Member</button>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h1>Event Not Exist</h1>
    {% endif %}
</div>
    
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    {% block css %}

    {% endblock css %}
    <link rel="stylesheet" href="{% static 'main/styles/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:800|Roboto&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'main/img/logo.png'%}">
    <title>{% block tittle %}{% endblock tittle %}</title>
</head>
<body>
        <!-- navbar section -->
        <div class="navbarku {% if color == 'red' %} red {% elif color == 'yellow'%} yellow {% endif %}" id="navbar">
            <div class="logo"><a href="" {% if color == 'red' or color == 'yellow' %} class="text-white" {% endif %}>Hello.</a></div>
            <div class="mobile-menu-button" id="mobile-menu-button" onclick="tooglebtn1()">
                <span {% if color == 'red' or color == 'yellow' %} class="white" {% endif%}></span>
                <span {% if color == 'red' or color == 'yellow' %} class="white" {% endif %}></span>
                <span {% if color == 'red' or color == 'yellow' %} class="white" {% endif%}></span>
            </div>
            <div class="selection">
                {% if color == 'none' %}
                <ul>
                    <li><a href="{% url 'polls:index' %}" class="nav-select">Home</a><span class="active"></span></li>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="#about" class="nav-select">About</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="#project" class="nav-select">Project</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select">Course</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select">Contact</a><span class="nav-line"></span></li>
                </ul>
                {% elif color == 'red' %}
                <ul>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="{% url 'polls:index' %}" class="nav-select text-white">Home</a><span class="nav-line white"></span></li>
                    <li><a href="" class="nav-select text-white">About</a><span class="active white"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:yellowSoon' %}" class="nav-select text-white">Project</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select text-white">Course</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select text-white">Contact</a><span class="nav-line white"></span></li>
                </ul>
                {% elif color == 'yellow'%}
                <ul>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="{% url 'polls:index' %}" class="nav-select text-white">Home</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:redSoon' %}" class="nav-select text-white">About</a><span class="nav-line white"></span></li>
                    <li><a href="" class="nav-select text-white">Project</a><span class="active white"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select text-white">Course</a><span class="nav-line white"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select text-white">Contact</a><span class="nav-line white"></span></li>
                </ul>
                {% else %}
                <ul>
                    <li onmouseover="lineover(0)" onmouseout="lineout(0)"><a href="{% url 'polls:index' %}" class="nav-select">Home</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:redSoon' %}" class="nav-select">About</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(1)" onmouseout="lineout(1)"><a href="{% url 'polls:yellowSoon' %}" class="nav-select">Project</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(2)" onmouseout="lineout(2)"><a href="{% url 'matakuliah:index' %}" class="nav-select">Course</a><span class="nav-line"></span></li>
                    <li onmouseover="lineover(3)" onmouseout="lineout(3)"><a href="#contact" class="nav-select">Contact</a><span class="nav-line"></span></li>
                </ul>
                {% endif %}
            </div>
        </div>
        <div class="big-nav {% if color == 'red' %} red {% elif color == 'yellow'%} yellow {% endif %}" id="select">
            {% if color == 'red' or color == 'yellow' %}
            <div class="selection" onclick="tooglebtn1()" >
                <a href="{% url 'polls:index' %}" class="text-white">Home</a>
                <a href="{% url 'polls:redSoon' %}" class="text-white">About</a>
                <a href="{% url 'matakuliah:index' %}" class="text-white">Course</a> 
                <a href="{% url 'polls:yellowSoon' %}" class="text-white">Project</a>
                <a href="#contact" class="text-white">Contact</a>
            </div>
            {% else %}
            <div class="selection" onclick="tooglebtn1()" >
                <a href="{% url 'polls:index' %}">Home</a>
                <a href="{% url 'polls:redSoon' %}">About</a>
                <a href="{% url 'matakuliah:index' %}">Course</a> 
                <a href="{% url 'polls:yellowSoon' %}">Project</a>
                <a href="#contact">Contact</a>
            </div>
            {% endif %}
        </div>
        <!-- endsection -->
        {% block content %}

        {% endblock content %}
        <!-- section footer -->
        <section class="footer" id="contact">
            <div class="email"><span>Email -- <a href="https://mail.google.com/mail/?to=inbox@example.com&bcc=admin@example.com&subject=Hey#compose">m.hafizmaulana777@gmail.com</a></span></div>
            <div class="socmed">
                <a href="https://www.linkedin.com/in/muhammad-hafiz-maulana-990980157/"><img src="{% static 'main/img/linkedin.png' %}" alt=""></a>
                <a href="https://twitter.com/mhdhafizmm"><img src="{% static 'main/img/twitter.png' %}" alt=""></a>
                <a href="http://line.me/ti/p/muhammadhafizm"><img src="{% static 'main/img/line.png' %}" alt=""></a>
                <a href="https://api.whatsapp.com/send?phone=6282247558182"><img src="{% static 'main/img/whatsap.png' %}" alt=""></a>
                <a href="https://www.instagram.com/muhammadhafizm/"><img src="{% static 'main/img/instagram.png' %}" alt=""></a>
            </div>
        </section>
        <!-- endsection -->
</body>

{% block js %} 

{% endblock js %}
<script src="{% static 'main/styles/navbar.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

testform1/templates/indexAdmin.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/styles/course.css' %}">
{% endblock css %}

{% block tittle %} Courses {% endblock tittle %}

{% block content %}
<div class="courses">
    <div class="header"><h1>Courses</h1></div>
    {% if matakuliah is not none %}
        <div class="table">
            {% for i in matakuliah %}
            <div class="card">
                <h5 class="card-header">{{ i.namaMatkul }}</h5>
                <div class="card-body">
                <h5 class="card-title">Jumlah SKS = {{i.jumlahSKS}}</h5>
                <p class="card-text">{{i.snippet}}</p>
                <a href="{% url 'matakuliah:showAdmin' order=i.order %}" class="btn btn-primary">Detail</a>
                <form action="" method="POST" class="delete-btn">
                    {% csrf_token %}
                    <input type="hidden" name="order" value="{{i.order}}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </div>
            </div>
            {% endfor %}
            <button type="button" class="btn btn-info" onclick="location.href='{% url 'matakuliah:create' %}'">Add Data</button>
        </div>
    {% else %}
    <h1>Courses Not Exist</h1>
    {% endif %}
</div>
    
{% endblock content %}

testform1/templates/matkul.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/styles/course.css' %}">
{% endblock css %}

{% block tittle %} Courses {% endblock tittle %}

{% block content %}
<div class="courses">
    <div class="header"><h1>Courses</h1></div>
    {% if matakuliah is not none %}
        <div class="table">
            {% for i in matakuliah %}
            <div class="card">
                <h5 class="card-header">{{ i.namaMatkul }}</h5>
                <div class="card-body">
                <h5 class="card-title">Jumlah SKS = {{i.jumlahSKS}}</h5>
                <p class="card-text">{{i.snippet}}</p>
                <a href="{% url 'matakuliah:show' order=i.order %}" class="btn btn-primary">Detail</a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
    <h1>Courses Not Exist</h1>
    {% endif %}
</div>
    
{% endblock content %}